management:
 endpoint:
   info:
     enabled: true  
   health:
     enabled: true
   shutdown:
     enabled: true
 endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:sqlite:MyMusic.db
    username: ""
    password: ""
    driver-class-name:  org.sqlite.JDBC
    database-platform: com.dojo.springboot.jpa.config.SQLiteDialect